apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-1
  namespace: client1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeName: pv-client1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-2
  namespace: client2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeName: pv-client2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-3
  namespace: client3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeName: pv-client3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-4
  namespace: client4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeName: pv-client4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-5
  namespace: client5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeName: pv-client5
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-6
  namespace: client6
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeName: pv-client6
